In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data"
column_names = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']
data = pd.read_csv(url, names=column_names)

# Замена пропущенных значений
data.replace('?', np.nan, inplace=True)

# Удаление строк с пропущенными значениями
data.dropna(inplace=True)

# Преобразование категориальных признаков в числовые значения
data['A1'] = data['A1'].map({'a': 0, 'b': 1})
data['A9'] = data['A9'].map({'t': 1, 'f': 0})
data['A10'] = data['A10'].map({'t': 1, 'f': 0})
data['A12'] = data['A12'].map({'t': 1, 'f': 0})
data['A16'] = data['A16'].map({'+': 1, '-': 0})

for col in ['A4', 'A5', 'A6', 'A7', 'A13']:
    data[col] = pd.Categorical(data[col]).codes

# Разделение данных на признаки (X) и целевую переменную (y)
X = data.drop("A16", axis=1)
y = data["A16"]

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Масштабирование данных
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Создание и обучение классификатора
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_train)

# Предсказания на тестовой выборке
y_pred = classifier.predict(X_test)

# Оценка производительности модели
print("Матрица ошибок:\n", confusion_matrix(y_test, y_pred))
print("\nОтчет о классификации:\n", classification_report(y_test, y_pred))
print("Точность модели:", accuracy_score(y_test, y_pred))


Матрица ошибок:
 [[66 10]
 [11 44]]

Отчет о классификации:
               precision    recall  f1-score   support

           0       0.86      0.87      0.86        76
           1       0.81      0.80      0.81        55

    accuracy                           0.84       131
   macro avg       0.84      0.83      0.84       131
weighted avg       0.84      0.84      0.84       131

Точность модели: 0.8396946564885496


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, mean_squared_error

# ... (здесь предобработка данных, как в предыдущем ответе) ...

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Масштабирование данных
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Создание и обучение логистической регрессии
logistic_classifier = LogisticRegression(random_state=42)
logistic_classifier.fit(X_train, y_train)

# Предсказания на тестовой выборке для логистической регрессии
logistic_y_pred = logistic_classifier.predict(X_test)

# Оценка производительности модели логистической регрессии
print("Логистическая регрессия:")
print("Матрица ошибок:\n", confusion_matrix(y_test, logistic_y_pred))
print("\nОтчет о классификации:\n", classification_report(y_test, logistic_y_pred))
print("Точность модели:", accuracy_score(y_test, logistic_y_pred))

Логистическая регрессия:
Матрица ошибок:
 [[62 14]
 [ 7 48]]

Отчет о классификации:
               precision    recall  f1-score   support

           0       0.90      0.82      0.86        76
           1       0.77      0.87      0.82        55

    accuracy                           0.84       131
   macro avg       0.84      0.84      0.84       131
weighted avg       0.85      0.84      0.84       131

Точность модели: 0.8396946564885496


In [ ]:
# Создание и обучение линейной регрессии
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)

# Предсказания на тестовой выборке для линейной регрессии
linear_y_pred = linear_regression.predict(X_test)

# Округление предсказаний линейной регрессии до ближайших 0 или 1
rounded_linear_y_pred = np.round(linear_y_pred).clip(0, 1).astype(int)

# Оценка производительности модели линейной регрессии
print("\nЛинейная регрессия:")
print("Матрица ошибок:\n", confusion_matrix(y_test, rounded_linear_y_pred))
print("\nОтчет о классификации:\n", classification_report(y_test, rounded_linear_y_pred))
print("Точность модели:", accuracy_score(y_test, rounded_linear_y_pred))
print("Среднеквадратическая ошибка:", mean_squared_error(y_test, linear_y_pred))


Линейная регрессия:
Матрица ошибок:
 [[60 16]
 [ 4 51]]

Отчет о классификации:
               precision    recall  f1-score   support

           0       0.94      0.79      0.86        76
           1       0.76      0.93      0.84        55

    accuracy                           0.85       131
   macro avg       0.85      0.86      0.85       131
weighted avg       0.86      0.85      0.85       131

Точность модели: 0.8473282442748091
Среднеквадратическая ошибка: 0.12746420160618932
